### PR TITLE
[WIP] Disable forcing default port for masternode setup

### PR DESCRIPTION
**Pull request by bedri**
This pull request simply disables default port forcing for masternodes.
**Alert: It should be tested very well before it's merged!!!**

### CODE REVIEW

**Comment by bedri** [comment]
image

Setting up masternodes will be tested on testnet now.

**Comment by bedri** [comment]
image

These 2 daemons running on the same server with different port and rpcport setup.
Setting up masternodes will be tested on testnet next.

**Comment by bedri** [comment]
image

Two masternode daemons can be run on the same server with different port and rpcport and for these two nodes we can setup 
two masternodes now.

port=xxxxx
rpcport=xxxxx
externalip=xxx.xxx.xxx.xxx

should be given in the daemon configuration file. For the first node it's not necessary to put externalip line but for all the extra nodes, externalip line should be put into the daemon config file.

**Comment by bedri** [comment]
I used https://github.com/tafali/kyanite-mn-guide to setup these two masternodes.
@tafali can you **_transfer_** repository to ```kyancoin``` user please?

**Comment by kyancoin** [comment]
Great work guys

Can we have a spork disabling and enabling it? it is safer to do it in that way.

**Comment by bedri** [comment]
> Great work guys
> 
> Can we have a spork disabling and enabling it? it is safer to do it in that way.

Yes sure.

**Comment by bedri** [comment]
Wallet seems not to connect to peers that runs wallet on a different port other than the default port but this does not prevent masternodes running in different ports on the same IP. This connection issue should be tested further. The issue does not affect the masternodes to run on different ports however it affects the network such that peers won't be connecting to masternodes running on different port other than the default port and get peer lists or blocks from them. To fix this, we need to adjust network connection rules. We may leave this adjustment for a later time (not accepting masternodes as "source-of-blocks") or we can make the fix now and then continue with the new release.

**Comment by bedri** [comment]
I got confused on the last commit name (https://github.com/kyancoin/KYAN/pull/17/commits/fa1c53f5cbaeb36efa3aeed066bf733646dbc713). It's not reverting a change but changing default port to the port given with the address (xxx.xxx.xxx.xxx:port).

**Comment by bedri** [comment]
Spork test for multiport enable/disable failed.
With multiport disabled in spork, I can still setup a new masternode with non-default port.
Moreover, currently running non-default port masternodes does not stop working. They should be rejected by the network if the multiport is disabled.
I will check it to find the problem(s).

**Pull request closed without merging**
