### PR TITLE
[WIP] Chainparameter, port, checkpoint and genesis block setup for four networks.

### PR DESCRIPTION
**Pull request by bedri**
Sets up new consensus parameters, ports, magic numbers, prefixes and new genesis blocks for mainnet, testnet, devnet and regtest.

### CODE REVIEW

**Comment by bedri** [comment]
@sapphire-pt this code will give assertion on genesis block transaction and spork key unless some codes aren't commented until it syncs blockchain from a peer. I had setup 2 testnet seed servers and will setup the nodes ASAP. There will be 4 blocks in mainnet (which we will clear them from all nodes and make mining start from block one) and 6+ blocks in testnet (I may mine some blocks on testnet until you compile and run this branch).

I will also document the codes that should be commented in case you need to create a new genesis block and mine the blocks alone.

**Comment by bedri** [comment]
BTW

> There will be 4 blocks in mainnet

I had to mine these for the genesis block validation assertion crashes go away.

**Comment by crypt0p3t3r** [comment]
Good job.

Can we create a method used with a command-line argument to mine a genesis block outputs it and another one to generate a spork key-pair and outputs it? after that, exit. 

It will be useful to launch the mainnet on the D-day and create testnet's when we need it, instead of commenting code on and off, which is very cumbersome.

It will be also useful for HELIO.

**Comment by bedri** [comment]
> Good job.
> 
> Can we create a method used with a command-line argument to mine a genesis block outputs it and another one to generate a spork key-pair and outputs it? after that, exit.
> 
> It will be useful to launch the mainnet on the D-day and create testnet's when we need it, instead of commenting code on and off, which is very cumbersome.
> 
> It will be also useful for HELIO.

Very good idea. I will look into it.

**Pull request merged**
